### ISSUE TITLE
Missing SSE polyfill

### ISSUE THREAD

**Issue by PeterWone** [greensponge/aurelia-dotnet-template#4]
To support HMR on Edge:

1. `npm i -s event-source-polyfill`
2. Modify webpack.config.js:29 to load the polyfill `vendor: ['bluebird','event-source-polyfill']`

**Comment by greensponge** [comment]
Thank you for helping out by reporting this, I tested it and Edge seems to connect to HMR fine now. I will close this issue as resolved now.
